version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: practicas-i-python-app:1.0  # Custom image name
    container_name: practicas-I-Python-App  # Explicit container name
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
