name: Practicas I CI/CD

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Checkout del repositorio
    - name: Checkout the repository
      uses: actions/checkout@v4

    # Paso 2: Configurar Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Paso 3: Iniciar sesión en Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Paso 4: Construir y etiquetar la imagen Docker
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: josojmf/practicas-i-dev:latest

    # Paso 5: Desplegar los servicios con Docker Compose
    - name: Deploy with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
